name: CI

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      # need to reinstall to synmlink binaries for integration tests now the cli tool is built
      - name: Reinstall
        run: |
          find . -name node_modules | xargs rm -rf
          yarn

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test -- -- --coverage

      - name: Test
        run: yarn test:integration
