name: Release

on:
  release:
    types: [published]

jobs:
  pipeline:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test -- -- --coverage

      - name: Integration test
        run: |
          # need to reinstall to synmlink binaries for integration tests now the cli tool is built
          find . -name node_modules | xargs rm -rf
          yarn
          yarn test:integration

      - name: Prep publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Publish prerelease
        if: "github.event.release.prerelease"
        run: |
          yarn run lerna publish --dist-tag next from-package --yes

      - name: Publish release
        if: "!github.event.release.prerelease"
        run: |
          yarn run lerna publish --dist-tag latest from-package --yes
