name: Release

on:
  push:
    tags:
      - release-*

jobs:
  pipeline:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test -- -- --coverage

      - name: Integration Test
        run: |
          # need to reinstall to synmlink binaries for integration tests now the cli tool is built
          find . -name node_modules | xargs rm -rf
          yarn
          yarn test:integration

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          yarn run lerna publish from-package --yes
