name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        working-directory: packages/cli
        run: yarn build

      - name: Reinstall
        run: |
          find . -name node_modules | xargs rm -rf
          yarn

      - name: Typecheck
        working-directory: packages/cli
        run: yarn typecheck

      - name: Lint
        working-directory: packages/cli
        run: yarn lint

      - name: Test
        working-directory: packages/cli
        run: yarn test

      - name: Run e2e tests
        working-directory: packages/private/e2e-tests
        run: yarn test
