name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        working-directory: packages/cli
        run: yarn build

      - name: Typecheck
        working-directory: packages/cli
        run: yarn typecheck

      - name: Lint
        working-directory: packages/cli
        run: yarn lint

      - name: Build test utils
        working-directory: packages/@helpers/test-utils
        run: yarn build

      - name: Run e2e tests
        run: yarn test:e2e:all
